### ISSUE TITLE
issu: spoofing with X-Forwarded-For is not working 

### ISSUE THREAD

**Issue by superuser5** [ustayready/fireprox#12]
The "Spoof X-Forwarded-For source IP header by requesting with an X-My-X-Forwarded-For header" is not working:

Request:
GET /fireprox/ HTTP/1.1
Host: 6dge1sxsw0.execute-api.us-west-2.amazonaws.com
Accept-Encoding: gzip, deflate
Accept: */*
Accept-Language: en
X-Forwarded-For: 1.1.1.1
X-Forwarded-Port: 4431
X-Forwarded-Proto: http
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36
Connection: close

request headers on the server-side, arrives with randomized IP, but with passed real IP:
X-Forwarded-For: 1.1.1.1, real.ip.real.ip
X-Forwarded-Port: 443
X-Forwarded-Proto: https
x-amzn-apigateway-api-id: 6dge1sxsw0

**Comment by ustayready** [comment]
Your request header shouldn't be X-Forwarded-For: 1.1.1.1, it should be X-My-X-Forwarded-For: 1.1.1.1
FireProx automatically replaces the X-Forwarded-For with whatever value you provide in the X-My-X-Forwarded-For header.
