### ISSUE TITLE
Basic usage questions - how to make use of in spider

### ISSUE THREAD

**Issue by jim256** [ustayready/fireprox#13]
I really apologize, because I feel like this is probably really obvious, but how do I really use this? I was looking over the examples, but was still kind of confused.

Is the --url argument supposed to be the domain of the site I'm going to be hitting? I'm using it for scraping. Do I run this once for each target site I want to scrape?

After I've run it, do I replace the domain of my target site in my spider code with the execute-api.us-east-2.amazonaws.com/fireprox/ URL? Or do I use that as my HTTP proxy? Or something else?

I'm using Scrapy. If I have something simple like:
```
    def start_requests(self):
        yield Request('http://thesiteiamcrawling.org/category/parameter', callback=self.parse)
```

Would I simply pass thesiteiamcrawling.org as the url argument when I run Fireprox and otherwise carry on as usual? 

How does the spider actually make use of the proxy when it tries to hit thesiteiamcrawling.org ? In the examples, it almost seemed like you just hit the same url you always would, and so I assumed Fireprox was rerouting requests that matched the domain passed to it in the url argument. Didn’t seem to work for me when I tried it in my spider, though.

Does the code that’s going to use the proxy also have to be Python 3.6? My spiders still need to be converted from 2.7.15.

I ran http.server the same as in the screenshots, but no traffic appeared.

Thank you so much!

**Comment by jim256** [comment]
Got it figured out. Didn’t realize that it was an actual public URL that I could hit from anywhere. Thanks for the awesome project!

**Comment by markkdev** [comment]
> Got it figured out. Didn’t realize that it was an actual public URL that I could hit from anywhere. Thanks for the awesome project!

Hey did you ever get this integrated with scrapy? 

I'm trying to figure out if you need to create a new URL with the script every time?
