### ISSUE TITLE
429 - Too Many Requests

### ISSUE THREAD

**Issue by alexvasiu** [ustayready/fireprox#16]
We tried to use it for google but when we are doing continuous requests for web crawling we end und up with `429 - Too Many Requests`. How often is the IP address rotating?

**Comment by ustayready** [comment]
Rotates every request. Make sure you are spoofing the X-Forwarded-For header. Not sure context, whatever you are doing is probably being fingerprinting on something else. Setup a simple web server and point FireProx to it then view the request headers.
