### ISSUE TITLE
Shows prompt "Unable to load AWS credentials"...Please help

### ISSUE THREAD

**Issue by IftequarIffu** [ustayready/fireprox#17]
python3 fire.py  --access_key ***************** --secret_access_key "******************************************" --region "us-east-1" --profile_name **** --command create --url "https://www.whatsmyip.org/"

The above command shows help output and then "Unable to load AWS credentials"

**Comment by z3dc0ps** [comment]
python3 fire.py --access_key "xxxxxxxx" --secret_access_key "xxxxxx" --region "us-east-1" --command create --url xxxxxx


this command works for me

**Comment by IftequarIffu** [comment]
Yeah brother....It works fine now...Actually, my AWS account payment was pending.. That was the reason for that

**Comment by mbb5546** [comment]
I am having this exact same issue. I am using AWS free tier so It's not a payment issue. Any advice or tips are appreciated this has been bothering me all day

**Comment by mbb5546** [comment]
Update: Still receiving "Unable to load AWS credentials"

I have closed my previous AWS account, created a new account, created a new API user with the proper permissions and have acquired a new set of access/Secret access keys. 

I have followed the basic install instructions and upon running `sudo python3 fire.py --access_key *******8 --secret_access_key ******************** --region us-east-2 --command create --url https://whatsmyip.org` 

I still receive an error stating "Unable to load AWS credentials". I thought this may have been an AWS issue but after creating a whole new AWS I am unsure if thats the case. Would appreciate any feedback/help here

**Comment by z3dc0ps** [comment]
Check whether the copied KEY/Secret KEY have spaces or not.
If there is a space remove that and try again.
## Full command :


    python fire.py --access_key "xxx" --secret_access_key "xxx" --region "xxx" --command create --url https://xxx.com

**Comment by ustayready** [comment]
Set them in the ~/.aws/credentials and pass the `--profile` parameter using the profile name.

Passing them in directly works for me fine.

**Comment by er4z0r** [comment]
This seems to occur on Windows. At least for me. Running fireprox with the same access key and secret key on my kali-box works.
