### ISSUE TITLE
Post Requests not working

### ISSUE THREAD

**Issue by rcaroncd** [ustayready/fireprox#22]
Hello,

I have tested the tool and, **when making GET requests, it works correctly**. The requests are made from different AWS IPs and arrive correctly at the web server. **But when I try to make POST requests** (for a password spraying or user enumeration attack, for example) the requests do not reach the web server and **I get a "Missing Authentication Token" error**. I have searched about this error and I think I should not specify any token when making cURL requests using the fireprox url as indicated in the tool. Does anyone know why this is happening? Maybe I am doing something wrong?

I ran the tool with the following command to create the AWS proxy:

```
python fire.py --access_key 'XXXX' --secret_access_key 'XXXX' --command create --url https://login.microsoftonline.com/common/GetCredentialType --region us-east-2
```

![issue_fireprox](https://user-images.githubusercontent.com/62614400/109809634-d7716100-7c28-11eb-81f5-c3bebd2430dd.png)

Thanks a lot for the tool, it's great!

**Comment by ustayready** [comment]
POST requests to the default / error out with "Missing Authentication Token" but if you POST to a URI then it will work. Sorry for the headaches.

Thx Fernando (rifle) for the help troubleshooting and finding a solution!

**Comment by Kankarollo** [comment]
I have the same issue. Can you explain in more details what's the solution?

**Comment by ustayready** [comment]
The syntax you used to create is wrong, you need to point the URL to the base `https://login.microsoftonline.com/`

The corrected syntax should be:
`python fire.py --access_key 'XXXX' --secret_access_key 'XXXX' --command create --url https://login.microsoftonline.com/ --region us-east-2`

Then when you spray, append your uri to /fireprox/
`https://login.microsoftonline.com/fireprox/common/GetCredentialType`
