### ISSUE TITLE
percentange symbol (%) causes 400 error

### ISSUE THREAD

**Issue by proabiral** [ustayready/fireprox#27]
Thank you for the awesome project.

When a percentage symbol is sent anywhere in the URL, the request is not proxied and 400 response is received.

![Screenshot from 2021-10-21 00-43-24](https://user-images.githubusercontent.com/22173232/138155489-c1ef256b-bc2c-4253-9dbc-e7a9d7971d75.png)

**Comment by ustayready** [comment]
If API Gateway isn't forwarding %'s correctly, that would be an AWS issue. Fireprox only sets up the API GW for you and manages it. Sorry!
