### ISSUE TITLE
`X-Forwarded-For` and other headers are still passed

### ISSUE THREAD

**Issue by moltar** [ustayready/fireprox#32]
It appears that all of the detectable headers are still included in the request.

Repro:

```sh
python fire.py --command=create --url=https://headers.cloxy.net/request.php
```

Then:

```sh
curl https://xyz.execute-api.ap-northeast-1.amazonaws.com/fireprox/ | grep '<li>'
```

---

```html
<li>Connection: close</li>
<li>Host: headers.cloxy.net</li>
<li>X-Amzn-Apigateway-Api-Id: xyz</li>
<li>X-Forwarded-Proto: https</li>
<li>X-Forwarded-Port: 443</li>
<li>X-Forwarded-For: 161.230.x.x</li>
<li>X-Amzn-Trace-Id: Root=1-62726bb1-7d733e213b3e1c624qwerty</li>
<li>User-Agent: Mozilla/5.0 (Windows NT 6.1; rv:31.0) Gecko/20100101 Firefox/31.0</li>
<li>Accept: */*</li>
```

**Comment by lampnout** [comment]
Hey moltar,

Check out the behavior when you add the custom header "X-My-X-Forwarded-For".

For example:

> curl -H "X-My-X-Forwarded-For" https://xyz.execute-api.ap-northeast-1.amazonaws.com/fireprox/ | grep '\<li\>'

@ustayready, when adding X-My-X-Forwarded-For, this header indeed overwrites the "X-Forwarded-For". However, it's also reflected on the request that goes to the destination server.

Is there a way to remove it?

**Comment by ustayready** [comment]
It's on my research list of things to-do. I mentioned to someone the other day that I was going to see if it's possible to force API GW to just strip them.

Closing out this issue since I see it's resolved with https://github.com/ustayready/fireprox/issues/32#issuecomment-1180701014
