### ISSUE TITLE
Is it possible to keep the same IP over several requests and change on a certain request?

### ISSUE THREAD

**Issue by ascheucher** [ustayready/fireprox#7]
I would like to simulate user sessions as close as possible. Hence, I need to switch IPs on defined number of page loads.
Is this possible with the API gateway method?

**Comment by ustayready** [comment]
I haven’t seen a way to do this with api gateway. An alternative is to use my other tool CredKing which uses AWS lambda. Each lambda region reuses the same ip for a short period of time.
