### ISSUE TITLE
X-fowared still being sent

### ISSUE THREAD

**Issue by updatesvc** [ustayready/fireprox#9]
it seems x-fowarded it still being sent.
I used the following site to check if headers were being sent.

here is the command to run.
`python fire.py  --access_key ACCESSKEY --secret_access_key SECRET --region us-west-2 --command create --api_id 1 --url http://www.whatismyproxy.com/`

result after visiting endpoint:
```
X-Forwarded-For: my actual ip
X-Forwarded-Port: 443
X-Forwarded-Proto: https
```

did the patch stop working?

**Comment by ustayready** [comment]
Just tested this using an HTTP Python server that dumps the headers and a new Fireprox proxy URL. Worked perfectly using curl and adding the header X-My-X-Forwarded-For pointing to a random IP.

Double check you are passing in the header properly, not sure what else I can do for this issue. Sorry!
